name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: Test (node ${{matrix.node}})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["10", "12", "14", "15"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Run tests
        run: npm test
